import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import Image from "next/image";
import mateDev from "../public/mateAvatar.png"; // Import using public folder
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Máté Egri Portfolio</title>
        <meta name="description" content="Generated by Next.js" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40"> {/* padding for */}
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            {" "}
            {/* padding top & bottom 10 */}
            <h1 className="text-xl font-extralight">developedbymaak</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium">
              Hi, I'm Máté Egri
            </h2>
            <h3 className="text-2xl py-2">Full-stack Developer and Designer</h3>
            <p className="text-md py-5 leading-8 text-gray-700">
              Freelancer Web-development Magician
            </p>
          </div>
          <div className="text-5xl flex justify-center gap 16 py-3 text-gray-600">
            <AiFillLinkedin />
            <AiFillGithub />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden">
            <Image
              src={mateDev}
              className="rounded-full"
              alt={"Cartonised profile picture"}
            />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py1">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-700">
              As a full stack web developer, I can help you build and maintain
              both the front-end and the back-end of your website or
              application. I have expertise in various technologies and
              frameworks, such as
              <span className="text-teal-500">
                HTML, CSS, JavaScript, React, Angular, Node.js, MongoDB, MySQL,
                Laravel
              </span>
              , and more. I can design and create user-friendly interfaces,
              <span className="text-teal-500">web services and APIs</span>, data
              storage and processing solutions, and other features that meet
              your business needs.
            </p>
            <p className="text-md py-2 leading-8 text-gray-700">
              I can also perform tests, troubleshoot software, fix bugs, and
              collaborate with other developers on projects. Whether you need a
              simple website or a complex web application, I can deliver
              high-quality and scalable full stack development solutions for
              you.
            </p>
          </div>
          <div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image
                src={design}
                width={100}
                height={100}
                className="text-center"
                alt={"design logo"}
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py2">Creating elegant designs</p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Affinity Photo</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image
                src={code}
                width={100}
                height={100}
                className="text-center"
                alt={"design logo"}
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py2">Creating elegant designs</p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Affinity Photo</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image
                src={consulting}
                width={100}
                height={100}
                className="text-center"
                alt={"design logo"}
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py2">Creating elegant designs</p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Affinity Photo</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py1">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-700">
              As a full stack web developer, I can help you build and maintain
              both the front-end and the back-end of your website or
              application. I have expertise in various technologies and
              frameworks, such as
              <span className="text-teal-500">
                HTML, CSS, JavaScript, React, Angular, Node.js, MongoDB, MySQL,
                Laravel
              </span>
              , and more. I can design and create user-friendly interfaces,
              <span className="text-teal-500">web services and APIs</span>, data
              storage and processing solutions, and other features that meet
              your business needs.
            </p>
          </div>
          <div>
            <Image src={web1} alt={"web design"}/>
          </div>
          <div>
            <Image src={web2} alt={"web design"}/>
          </div>
          <div>
            <Image src={web3} alt={"web design"}/>
          </div>
          <div>
            <Image src={web4} alt={"web design"}/>
          </div>
          <div>
            <Image src={web5} alt={"web design"}/>
          </div>
          <div>
            <Image src={web6} alt={"web design"}/>
          </div>
        </section>
      </main>
    </div>
  );
}
