import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Máté Egri Portfolio</title>
        <meta name="description" content="Generated by Next.js" />
      </Head>
      <main></main>
    </div>
  );
}
